Sun Apr 19 22:37:08 2020
Traceback (most recent call last):
  File "D:\kfw_dev\load game.py", line 7, in <module>
    g.load_game('save.txt')
  File "D:\kfw_dev\kf_lib\game.py", line 323, in load_game
    exec(line)
  File "<string>", line 1, in <module>
  File "D:\kfw_dev\kf_lib\player.py", line 57, in __init__
    tech_names=tech_names, move_names=move_names, rand_atts_mode=rand_atts_mode)
  File "D:\kfw_dev\kf_lib\fighter.py", line 207, in __init__
    self.set_moves(move_names)
  File "D:\kfw_dev\kf_lib\fighter.py", line 1051, in set_moves
    self.learn_move(mn, silent=True)  # not to write log every time (e.g. when loading a game)
  File "D:\kfw_dev\kf_lib\fighter.py", line 895, in learn_move
    move = moves.get_move_obj(move)
  File "D:\kfw_dev\kf_lib\moves.py", line 138, in get_move_obj
    return ALL_MOVES_DICT[move_name]
KeyError: 'Iron Fist'
